"""
modules/tls/controller.py — Module 8: TLS Configuration Advisor

Operations:
  - inspect_remote: run s_client against a host, parse TLS details
  - build_config: generate a secure TLS config snippet for Nginx/Apache/etc.
  - rate_config: score a TLS configuration (Mozilla-style)
"""

import re

from core.audit_log import log_operation
from core.executor import run_openssl
from core.result import ExecutionResult

# Mozilla Intermediate profile (recommended for most services)
MOZILLA_INTERMEDIATE = {
    "tls_versions": ["TLSv1.2", "TLSv1.3"],
    "tls13_ciphers": "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256",
    "tls12_ciphers": (
        "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:"
        "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:"
        "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:"
        "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
    ),
    "dh_bits": 2048,
    "ecdh_curves": "X25519:prime256v1:secp384r1",
    "hsts_max_age": 63072000,
}

# Mozilla Modern profile (TLS 1.3 only)
MOZILLA_MODERN = {
    "tls_versions": ["TLSv1.3"],
    "tls13_ciphers": "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256",
    "dh_bits": None,
    "ecdh_curves": "X25519:prime256v1:secp384r1",
    "hsts_max_age": 63072000,
}

_SERVER_TEMPLATES = {
    "nginx": {
        "intermediate": """\
# Mozilla Intermediate TLS configuration for Nginx
# Generated by sslOpenCrypt — https://tctech.co.in
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;
ssl_session_tickets off;
ssl_dhparam /etc/nginx/dhparam.pem;  # openssl dhparam -out /etc/nginx/dhparam.pem 2048
ssl_ecdh_curve X25519:prime256v1:secp384r1;
add_header Strict-Transport-Security "max-age=63072000" always;
ssl_stapling on;
ssl_stapling_verify on;
""",
        "modern": """\
# Mozilla Modern TLS configuration for Nginx (TLS 1.3 only)
# Generated by sslOpenCrypt — https://tctech.co.in
ssl_protocols TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;
ssl_session_tickets off;
ssl_ecdh_curve X25519:prime256v1:secp384r1;
add_header Strict-Transport-Security "max-age=63072000" always;
ssl_stapling on;
ssl_stapling_verify on;
""",
    },
    "apache": {
        "intermediate": """\
# Mozilla Intermediate TLS configuration for Apache httpd
# Generated by sslOpenCrypt — https://tctech.co.in
SSLEngine on
SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLHonorCipherOrder     off
SSLSessionTickets       off
SSLOpenSSLConfCmd DHParameters "/etc/ssl/certs/dhparam.pem"
SSLOpenSSLConfCmd ECDHParameters "X25519:prime256v1:secp384r1"
Header always set Strict-Transport-Security "max-age=63072000"
SSLUseStapling On
SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"
""",
    },
    "haproxy": {
        "intermediate": """\
# Mozilla Intermediate TLS configuration for HAProxy
# Generated by sslOpenCrypt — https://tctech.co.in
global
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
    tune.ssl.default-dh-param 2048
""",
    },
    "postfix": {
        "intermediate": """\
# Mozilla Intermediate TLS for Postfix SMTP
# Generated by sslOpenCrypt — https://tctech.co.in
smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtpd_tls_mandatory_ciphers = high
smtpd_tls_ciphers = high
tls_high_cipherlist = ECDHE+aGCM:DHE+aGCM
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
""",
    },
}


def inspect_remote(host: str, port: int = 443, starttls: str | None = None) -> ExecutionResult:
    """
    Retrieve and display TLS handshake details for a remote host.
    starttls: None | "smtp" | "imap" | "ftp"
    """
    cmd = [
        "s_client",
        "-connect", f"{host}:{port}",
        "-servername", host,
        "-status",
        "-tlsextdebug",
    ]
    if starttls:
        cmd += ["-starttls", starttls]

    r = run_openssl(cmd, input_data=b"Q\n", timeout=20)

    if r.stdout or r.stderr:
        combined = r.stdout + r.stderr
        r.parsed["host"] = host
        r.parsed["port"] = port

        m = re.search(r"Protocol\s*:\s*(.+)", combined)
        if m:
            r.parsed["protocol"] = m.group(1).strip()

        m = re.search(r"Cipher\s*:\s*(.+)", combined)
        if m:
            r.parsed["cipher"] = m.group(1).strip()

        subjects = re.findall(r"subject=(.+)", combined)
        r.parsed["subjects"] = [s.strip() for s in subjects]

        issuers = re.findall(r"issuer=(.+)", combined)
        r.parsed["issuers"] = [i.strip() for i in issuers]

        m = re.search(r"Server public key is (\d+) bit", combined)
        if m:
            r.parsed["server_key_bits"] = int(m.group(1))

    log_operation("tls", f"inspect_remote:{host}:{port}", r.command_str, r.success or bool(r.stdout))
    return r


def build_config(
    server: str = "nginx",
    profile: str = "intermediate",  # "intermediate" | "modern"
    include_dhparam_cmd: bool = True,
) -> str:
    """Return a ready-to-paste TLS configuration snippet."""
    server = server.lower()
    profile = profile.lower()

    templates = _SERVER_TEMPLATES.get(server, {})
    config = templates.get(profile, templates.get("intermediate", ""))

    if not config:
        config = f"# No template available for {server} {profile}\n# See https://ssl-config.mozilla.org\n"

    if include_dhparam_cmd and "dhparam" not in config and server != "haproxy":
        config += "\n# Generate DH parameters:\n# openssl dhparam -out /etc/ssl/dhparam.pem 2048\n"

    return config


def rate_config(tls_versions: list[str], ciphers: str) -> dict:
    """
    Rate a TLS configuration against Mozilla profiles.
    Returns grade: A+ / A / B / C / F and explanation.
    """
    score = 100
    issues = []
    recommendations = []

    versions_lower = [v.lower() for v in tls_versions]

    if "sslv3" in versions_lower or "sslv2" in versions_lower:
        score -= 40
        issues.append("SSLv3/SSLv2 enabled — completely broken, disable immediately")

    if "tlsv1" in versions_lower or "tlsv1.0" in versions_lower:
        score -= 20
        issues.append("TLS 1.0 enabled — deprecated and insecure")

    if "tlsv1.1" in versions_lower:
        score -= 10
        issues.append("TLS 1.1 enabled — deprecated")

    if not any(v in versions_lower for v in ["tlsv1.2", "tlsv1.3"]):
        score -= 30
        issues.append("Neither TLS 1.2 nor TLS 1.3 is enabled")

    ciphers_lower = ciphers.lower()
    if "rc4" in ciphers_lower:
        score -= 30
        issues.append("RC4 in cipher suite — broken, RFC 7465 prohibited")
    if "3des" in ciphers_lower or "des-ede" in ciphers_lower:
        score -= 20
        issues.append("3DES in cipher suite — vulnerable to SWEET32 (CVE-2016-2183)")
    if "export" in ciphers_lower:
        score -= 30
        issues.append("EXPORT-grade ciphers — broken")
    if "null" in ciphers_lower or "_null_" in ciphers_lower:
        score -= 40
        issues.append("NULL ciphers — no encryption")

    if not any(kw in ciphers_lower for kw in ["gcm", "chacha20", "poly1305"]):
        score -= 10
        recommendations.append("Consider adding AEAD ciphers (GCM, ChaCha20-Poly1305)")

    if "tlsv1.3" not in versions_lower:
        recommendations.append("Enable TLS 1.3 for improved performance and security")

    score = max(0, min(100, score))
    if score >= 90:
        grade = "A+"
    elif score >= 80:
        grade = "A"
    elif score >= 70:
        grade = "B"
    elif score >= 60:
        grade = "C"
    else:
        grade = "F"

    return {
        "grade": grade,
        "score": score,
        "issues": issues,
        "recommendations": recommendations,
        "mozilla_profile": "Modern" if tls_versions == ["TLSv1.3"] else "Intermediate-compatible" if score >= 80 else "Below-recommended",
    }


def list_ciphers_for_host(host: str, port: int = 443) -> ExecutionResult:
    """List cipher suites accepted by a remote TLS server (informational, via s_client)."""
    cmd = ["s_client", "-connect", f"{host}:{port}", "-servername", host, "-cipher", "ALL:@SECLEVEL=0"]
    r = run_openssl(cmd, input_data=b"Q\n", timeout=20)
    log_operation("tls", f"list_ciphers:{host}", r.command_str, r.success or bool(r.stdout))
    return r
